In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("FoodPrice_in_Turkey.csv", header=0, encoding='ISO-8859-1')
display(data)
data.info()

,Place,ProductId,ProductName,UmId,UmName,Month,Year,Price
0,National Average,52,Rice - Retail,5,KG,5,2013,4.4920
1,National Average,52,Rice - Retail,5,KG,6,2013,4.5786
2,National Average,52,Rice - Retail,5,KG,11,2013,4.7865
3,National Average,52,Rice - Retail,5,KG,12,2013,5.1337
4,National Average,52,Rice - Retail,5,KG,1,2014,5.5099
...,...,...,...,...,...,...,...,...
7376,Izmir,502,Cocoa (powder) - Retail,5,KG,8,2019,47.9040
7377,Izmir,502,Cocoa (powder) - Retail,5,KG,9,2019,49.1176
7378,Izmir,502,Cocoa (powder) - Retail,5,KG,10,2019,50.8347
7379,Izmir,502,Cocoa (powder) - Retail,5,KG,11,2019,51.7985
7380,Izmir,502,Cocoa (powder) - Retail,5,KG,12,2019,51.6071

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7381 entries, 0 to 7380
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Place        7381 non-null   object
 1   ProductId    7381 non-null   int64
 2   ProductName  7381 non-null   object
 3   UmId         7381 non-null   int64
 4   UmName       7381 non-null   object
 5   Month        7381 non-null   int64
 6   Year         7381 non-null   int64
 7   Price        7381 non-null   float64
dtypes: float64(1), int64(4), object(3)
memory usage: 461.4+ KB

In [2]:
print('Số dòng:', data.shape[0],'và số cột:', data.shape[1])

Số dòng: 7381 và số cột: 8

In [3]:
print('Thuộc tính của', data.columns[0], 'là định danh nominal')
print('Thuộc tính của', data.columns[1], 'là định danh nominal')
print('Thuộc tính của', data.columns[2], 'là định danh nominal')
print('Thuộc tính của', data.columns[3], 'là định danh nominal')
print('Thuộc tính của', data.columns[4], 'là định danh nominal')
print('Thuộc tính của', data.columns[5], 'là định danh nominal')
print('Thuộc tính của', data.columns[6], 'là định danh nominal')
print('Thuộc tính của', data.columns[7], 'là định tính ratio')

Thuộc tính của Place là định danh nominal
Thuộc tính của ProductId là định danh nominal
Thuộc tính của ProductName là định danh nominal
Thuộc tính của UmId là định danh nominal
Thuộc tính của UmName là định danh nominal
Thuộc tính của Month là định danh nominal
Thuộc tính của Year là định danh nominal
Thuộc tính của Price là định tính ratio

In [6]:
# giá trị trung bình từng loại thực phẩm
tb_sanpham = data.groupby(data.columns[2])[data.columns[7]].mean()
display(tb_sanpham)

ProductName
Apples (red) - Retail                                       2.392193
Apples - Retail                                             3.885039
Bananas - Retail                                            8.224784
Beans (white) - Retail                                      9.572830
Bread (common) - Retail                                     4.463293
Bread (pita) - Retail                                       2.404545
Bulgur - Retail                                             3.516712
Cabbage - Retail                                            1.723395
Cauliflower - Retail                                        3.274868
Cheese - Retail                                            25.522875
Chickpeas - Retail                                         10.347860
Cocoa (powder) - Retail                                    43.802339
Coffee (instant) - Retail                                  43.295493
Coffee - Retail                                            42.468075
Cucumbers (greenhouse) - Retail                             2.206807
Cucumbers - Retail                                          3.411326
Eggplants - Retail                                          3.882645
Eggs - Retail                                               0.505925
Electricity - Retail                                        0.513580
Fish (fresh) - Retail                                      22.698257
Fuel (gas) - Retail                                        83.976703
Fuel (petrol-gasoline) - Retail                             8.592519
Garlic - Retail                                            16.610370
Groundnuts (shelled) - Retail                              21.832122
Lentils - Retail                                            6.651817
Meat (chicken) - Retail                                     9.683471
Meat (mutton) - Retail                                     45.557209
Meat (veal) - Retail                                       41.270904
Milk (pasteurized) - Retail                                 3.679687
Milk (powder, infant formula) - Retail                    108.287696
Oil (olive) - Retail                                       27.274547
Oil (sunflower) - Retail                                    8.755174
Onions - Retail                                             2.141539
Oranges - Retail                                            3.124280
Pasta - Retail                                              3.496637
Peas (green, dry) - Retail                                  2.900029
Potatoes - Retail                                           2.297231
Rice - Retail                                               7.950325
Salt - Retail                                               2.048213
Spinach - Retail                                            3.240587
Sugar - Retail                                              4.482942
Tea (green) - Retail                                        4.137000
Tea (herbal) - Retail                                       5.434838
Tea - Retail                                               26.224393
Tomatoes (paste) - Retail                                   8.085128
Tomatoes - Retail                                           3.393658
Transport (public) - Retail                                 2.468031
Wage (non-qualified labour, non-agricultural) - Retail     40.548182
Water - Retail                                              5.384253
Wheat flour - Retail                                        3.253174
Yogurt - Retail                                             5.364898
Zucchini - Retail                                           3.837423
Name: Price, dtype: float64